# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2652312b9aea0386aa421be84c653e0ea88b4104c1991a9af3b81b8ce935ca10af7a3001217c06dcff1630b4719892ad0da097119476ba658a2e98410f76b379

test:
  secret_key_base: 8e89532d9710b88f526d21959c59b9bd7f0fdaf79ea9a369bc5a83676004aa065dab37ff2a1ec0dc4a8ca51766819f44ad1b57dc25c68be295c30897c512d525

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
